const DATA_URL = 'https://raw.githubusercontent.com/RhoInc/data-library/master/data/clinical-trials/renderer-specific/adbds.csv';
const state = {};
let chart;
function uniq(a){ return [...new Set(a.filter(v => v !== undefined && v !== null && v !== ''))].sort((x,y)=>String(x).localeCompare(String(y), undefined, {numeric:true})); }
function mean(vals){ vals = vals.map(Number).filter(Number.isFinite); return vals.length ? vals.reduce((a,b)=>a+b,0)/vals.length : null; }
function el(tag, attrs={}, text=''){ const e=document.createElement(tag); Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v)); if(text) e.textContent=text; return e; }
function select(label, values, value){ const w=el('div',{class:'control'}); w.append(el('label',{},label)); const s=el('select'); values.forEach(v=>{const o=el('option',{value:v},v); if(v===value) o.selected=true; s.append(o);}); w.append(s); return [w,s]; }
function input(label, value=''){ const w=el('div',{class:'control'}); w.append(el('label',{},label)); const i=el('input',{type:'number', value}); w.append(i); return [w,i]; }
function table(rows, cols){ return `<table><thead><tr>${cols.map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody>${rows.slice(0,50).map(r=>`<tr>${cols.map(c=>`<td>${r[c] ?? ''}</td>`).join('')}</tr>`).join('')}</tbody></table>`; }
function participantNote(rows, allRows){ const ids=uniq(rows.map(d=>d.USUBJID)); const total=uniq(allRows.map(d=>d.USUBJID)).length; return `${ids.length} of ${total} participants shown (${total ? (100*ids.length/total).toFixed(1) : '0.0'}%).`; }

d3.csv(DATA_URL).then(data => { const measures=['Albumin','Creatinine','Total Bilirubin']; const app=document.getElementById('app'); app.innerHTML='<div class="controls"></div><div class="note" id="note"></div><div class="grid" id="charts"></div>'; const controls=app.querySelector('.controls'); const [xW,xS]=select('X-axis',['VISITN','VISIT','DY'],'VISITN'), [nW,nS]=select('Normal Range Method',['LLN/ULN','None'],'LLN/ULN'); const cb=document.createElement('input'); cb.type='checkbox'; const cW=el('div',{class:'control'}); cW.append(el('label',{},'View Normal Range Inliers'),cb); controls.append(xW,nW,cW); [xS,nS,cb].forEach(x=>x.onchange=render); function render(){ const charts=document.getElementById('charts'); charts.innerHTML=''; measures.forEach((m,i)=>{let rows=data.filter(d=>d.TEST===m&&d.STRESN&&d[xS.value]); const inliers=rows.filter(d=>nS.value!=='None'&&+d.STRESN>=+d.STNRLO&&+d.STRESN<=+d.STNRHI); if(!cb.checked && nS.value!=='None') rows=rows.filter(d=>!inliers.includes(d)); const box=el('section',{class:'panel'}); box.innerHTML=`<h2>${m}</h2><p>${inliers.length} inlier records hidden</p><canvas></canvas>`; charts.append(box); const xs=uniq(rows.map(d=>d[xS.value])); new Chart(box.querySelector('canvas'),{type:'line',data:{labels:xs,datasets:[{label:m,data:xs.map(x=>mean(rows.filter(d=>d[xS.value]===x).map(d=>d.STRESN))),borderColor:['#2563eb','#16a34a','#dc2626'][i]}]},options:{plugins:{legend:{display:false}},scales:{x:{title:{display:true,text:xS.value}},y:{title:{display:true,text:'Mean non-inlier result'}}}}}); }); document.getElementById('note').textContent='Panels update when normal-range controls change.';} render(); });
